### ISSUE TITLE
Correct Killed (various errors)

### ISSUE THREAD

**Issue by apeltzer** [BUStools/bustools#6]
Hi! 

thanks for working on this - the entire process following the tutorial seemed fairly easy to understand so I gave it a shot to implement that basic workflow in the https://github.com/nf-core/scrnaseq pipeline. However, I get some issues with applying the correction + sorting step, mainly as this error pops up:

```

Command executed:

  bustools correct -w 10x_V3_barcode_whitelist -p S10_L001_bus_output/output.bus | bustools sort -T tmp/ -t 2 -m 6G -o S10_L001_bus_output/output.correct.sort.bus -

Command exit status:
  137

Command output:
  (empty)

Command error:
  Found 6794880 barcodes in the whitelist
  .command.sh: line 2:    30 Killed                  bustools correct -w 10x_V3_barcode_whitelist -p S10_L001_bus_output/output.bus
          31                       | bustools sort -T tmp/ -t 2 -m 6G -o S10_L001_bus_output/output.correct.sort.bus -
```

Any idea what I might do wrong here? Happy to help with bugreports / crash dumps etc if that is of help. I use the bioconda recipe for bustools and kallisto, the kallisto output seems to be fine (?) and all the files mentioned in the tutorial seem to be there too. 

I'm running 10X V2 data, all available from here and was running only against one chromosome of mouse to keep runtimes low for continous integrating testing purposes of the pipeline: https://github.com/nf-core/test-datasets/tree/scrnaseq 

Logfile/CI Run of the error message can be found here for example:

https://travis-ci.com/nf-core/scrnaseq/jobs/210270388

**Comment by pmelsted** [comment]
Two things.

1.
I think the `correct` command job was killed because of memory constraints. The current implementation of correct requires about 11G of memory and your spec says it has 6G available.

The memory usage is a top priority to fix for us.

2.
The data you are using has 26bp bc+UMI which is 10xv2, this has a smaller whitelist and will use less memory. There might also be an error because of the barcode whitelist vs BUS mismatch, I should check.

Both of these things should be fixed by using the v2 whitelist.

**Comment by apeltzer** [comment]
Hi Páll! 

thanks for these super quick replies. I will try to run the testing command for 1.) then with more memory and/or skip correction for now for the continuous integration testing part. 

I also changed to using the v2 whitelist - will keep you posted whether this helps 👍

**Comment by apeltzer** [comment]
Okay it was indeed an issue with memory and the correction step. When I run the pipeline without the correction, it works fine and uses 7.96GB of memory: 

![newplot](https://user-images.githubusercontent.com/2359510/60264370-54d8c000-98e3-11e9-85ed-3fcacdf97cbe.png)

When applying the correction step on the data I'm using, I unfortunately still get the same behaviour. I gave the process a total of 80GB of memory, which should be sufficient I think. 

```

  Found 737280 barcodes in the whitelist
  Number of hamming dist 1 barcodes = 20550336
  .command.sh: line 2:    28 Broken pipe             bustools correct -w 10x_V2_barcode_whitelist -p S10_L001_bus_output/output.bus
          29 Killed                  | bustools sort -T tmp/ -t 2 -m 80G -o S10_L001_bus_output/output.correct.sort.bus -

```

**Comment by apeltzer** [comment]
Okay, so I got a little mock dataset to be running using a subset of the whitelist - running in production will anyways require much more memory which is fine for us 👍 Thanks a bunch for working on this toolset!

**Comment by apeltzer** [comment]
I fear I need to reopen this issue, as the `bustools correct` command doesn't work for me here, unfortunately.

x-ref: https://github.com/nf-core/scrnaseq/issues/12 

Tried running with the https://www.kallistobus.tools/getting_started_explained.html data:

```bash
Command error:
  Found 737280 barcodes in the whitelist
  Number of hamming dist 1 barcodes = 20550336
  .command.sh: line 2:    28 Broken pipe             bustools correct -w 10xv2_whitelist.txt -p SRR8599150_S1_L001_R_bus_output/output.bus
          29 Killed                  | bustools sort -T tmp/ -t 10 -m 64G -o SRR8599150_S1_L001_R_bus_output/output.correct.sort.bus -

Work dir:
  /home/apeltzer/nf-core/scrnaseq/work/be/b35685507430590b9316a2e301a8ef
```

**Comment by apeltzer** [comment]
It is definitely an issue with `correct` and not with `sort` - if I configure my pipeline to not correct the data, we successfully create a sorted BUS file.

**Comment by pmelsted** [comment]
I've tried to recreate the issue using the exact same dataset. If the error is happening in the correct step, can you run it without the pipe to see why it was killed?

The command should be 
`bustools correct -w 10xv2_whitelist.txt  SRR8599150_S1_L001_R_bus_output/output.bus -o  SRR8599150_S1_L001_R_bus_output/output.corrected.bus`

**Comment by apeltzer** [comment]
Okay, its something with the piping between the two steps. I was successfully able to run the command when having an intermediate output file!
